root := "../.."
proto := root + "/src/Debug/debug.proto"

schema:
    protoc -I {{root}}/src/Debug --include_imports --include_source_info --descriptor_set_out=debug.pb {{proto}}

check:
    cargo check --workspace

test:
    cargo test --workspace

run device: schema
    cargo run -p console -- --device {{device}}

dap-server address:
    cargo run -p warduino-dap -- --dap-server {{address}}

build: schema
    cargo build --release -p console
