Output assets/demo.gif

# Set up a 1200x600 terminal with 28px font.
Set FontSize 21
Set Width 2100
Set Height 900
Set Margin 0
Set BorderRadius 20
Set Framerate 60
Set Theme "Catppuccin Mocha"

Type@50ms  "syrup --device localhost:8192"
Sleep 50ms
Enter

Sleep 1s

Type@300ms "Ste"
Tab@800ms 2
Enter

Sleep 5ms

Type@300ms "ste"
Tab@800ms 1
Enter

Sleep 5s

Type@300ms "cont"
Tab@150ms
Enter

Sleep 6s

Type@300ms "pau"
Tab@150ms
Enter

Sleep 2s

Shift+Tab
Enter

Up@3s 3

Sleep 2s

Up@200ms 17

Sleep 2s

