/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_DEBUG_DEBUG_PB_H_INCLUDED
#define PB_DEBUG_DEBUG_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Frontend -> WARDuino.
 The receiver selects the payload schema from the command byte. */
typedef enum _debug_Command {
    debug_Command_COMMAND_RUN = 0, /* no payload */
    debug_Command_COMMAND_HALT = 1, /* no payload */
    debug_Command_COMMAND_PAUSE = 2, /* no payload */
    debug_Command_COMMAND_STEP = 3, /* no payload */
    debug_Command_COMMAND_STEP_OVER = 4, /* no payload */
    debug_Command_COMMAND_ADD_BREAKPOINT = 5, /* Breakpoint */
    debug_Command_COMMAND_REMOVE_BREAKPOINT = 6, /* Breakpoint */
    debug_Command_COMMAND_CLEAR_BREAKPOINTS = 7, /* no payload */
    debug_Command_COMMAND_SNAPSHOT = 9, /* no payload */
    debug_Command_COMMAND_UPDATE_FUNCTION = 12, /* Function */
    debug_Command_COMMAND_UPDATE_LOCAL = 13, /* ValueUpdate */
    debug_Command_COMMAND_UPDATE_CALLBACKS = 14, /* CallbackMapping */
    debug_Command_COMMAND_UPDATE_MODULE = 26, /* ModuleUpdate */
    debug_Command_COMMAND_UPDATE_GLOBAL = 27, /* ValueUpdate */
    debug_Command_COMMAND_UPDATE_STACK = 28, /* ValueUpdate */
    debug_Command_COMMAND_LOAD_SNAPSHOT = 15, /* Snapshot */
    debug_Command_COMMAND_PROXIFY = 16, /* no payload */
    debug_Command_COMMAND_ADD_PROXY = 17, /* FunctionRef */
    debug_Command_COMMAND_REMOVE_PROXY = 18, /* FunctionRef */
    debug_Command_COMMAND_PROXY_CALL = 19, /* RemoteFunctionCall */
    debug_Command_COMMAND_POP_EVENT = 20, /* no payload */
    debug_Command_COMMAND_PUSH_EVENT = 21, /* Event */
    debug_Command_COMMAND_CONTINUE_FOR = 22, /* ContinueFor */
    debug_Command_COMMAND_INSPECT = 23, /* Inspect */
    debug_Command_COMMAND_RESET = 24, /* no payload */
    debug_Command_COMMAND_INVOKE = 25, /* RemoteFunctionCall */
    debug_Command_COMMAND_SET_SNAPSHOT_POLICY = 29, /* SnapshotPolicyConfig */
    debug_Command_COMMAND_SET_OVERRIDE = 30, /* Override */
    debug_Command_COMMAND_REMOVE_OVERRIDE = 31 /* Override */
} debug_Command;

/* WARDuino -> frontend.
 The receiver selects the payload schema from the notification byte. */
typedef enum _debug_NotificationType {
    debug_NotificationType_NOTIFICATION_CONTINUED = 0, /* no payload */
    debug_NotificationType_NOTIFICATION_HALTED = 1, /* no payload */
    debug_NotificationType_NOTIFICATION_PAUSED = 2, /* no payload */
    debug_NotificationType_NOTIFICATION_STEPPED = 3, /* no payload */
    debug_NotificationType_NOTIFICATION_HIT_BREAKPOINT = 4, /* HitBreakpoint */
    debug_NotificationType_NOTIFICATION_NEW_EVENT = 5, /* NewEvent (zero-length payload) */
    debug_NotificationType_NOTIFICATION_FUNCTION_DUMP = 6, /* Function */
    debug_NotificationType_NOTIFICATION_LOCALS_DUMP = 7, /* Locals */
    debug_NotificationType_NOTIFICATION_SNAPSHOT = 8, /* Snapshot */
    debug_NotificationType_NOTIFICATION_EVENTS_DUMP = 9, /* EventsQueue */
    debug_NotificationType_NOTIFICATION_CALLBACKS_DUMP = 10, /* CallbackMapping */
    debug_NotificationType_NOTIFICATION_CHANGE_AFFECTED = 11, /* no payload */
    debug_NotificationType_NOTIFICATION_MALFORMED = 12, /* no payload */
    debug_NotificationType_NOTIFICATION_UNKNOWN_COMMAND = 13, /* no payload */
    debug_NotificationType_NOTIFICATION_OPERATION_RESULT = 14, /* OperationResult */
    debug_NotificationType_NOTIFICATION_REMOTE_FUNCTION_RESULT = 15, /* RemoteFunctionResult */
    debug_NotificationType_NOTIFICATION_CHECKPOINT = 16 /* Checkpoint */
} debug_NotificationType;

typedef enum _debug_State {
    debug_State_STATE_WARDUINO_RUN = 0,
    debug_State_STATE_WARDUINO_PAUSE = 1,
    debug_State_STATE_WARDUINO_STEP = 2,
    debug_State_STATE_PROXY_RUN = 3,
    debug_State_STATE_PROXY_HALT = 4
} debug_State;

typedef enum _debug_SnapshotPolicy {
    debug_SnapshotPolicy_SNAPSHOT_POLICY_NONE = 0,
    debug_SnapshotPolicy_SNAPSHOT_POLICY_EVERY_INSTRUCTION = 1,
    debug_SnapshotPolicy_SNAPSHOT_POLICY_CHECKPOINTING = 2
} debug_SnapshotPolicy;

/* Struct definitions */
/* A virtual program address. */
typedef struct _debug_CodeLocation {
    uint32_t module_index;
    uint32_t program_counter;
} debug_CodeLocation;

typedef struct _debug_Breakpoint {
    bool has_location;
    debug_CodeLocation location;
} debug_Breakpoint;

typedef struct _debug_HitBreakpoint {
    bool has_location;
    debug_CodeLocation location;
} debug_HitBreakpoint;

/* The notification type carries all information for this event. The empty
 message exists for host-side reflection, but no protobuf bytes are sent. */
typedef struct _debug_NewEvent {
    char dummy_field;
} debug_NewEvent;

typedef struct _debug_ContinueFor {
    uint32_t count;
} debug_ContinueFor;

/* Execution-state selectors understood by the VM. Keeping them as bytes lets
 the protocol add selectors without changing this schema. */
typedef struct _debug_Inspect {
    pb_callback_t state;
} debug_Inspect;

typedef struct _debug_FunctionRef {
    uint32_t function_index;
} debug_FunctionRef;

typedef struct _debug_RemoteFunctionCall {
    uint32_t function_index;
    pb_callback_t arguments;
} debug_RemoteFunctionCall;

typedef struct _debug_CallstackEntry {
    uint32_t type;
    uint32_t function_index;
    uint32_t stack_pointer;
    uint32_t frame_pointer;
    uint32_t start;
    uint32_t return_address;
} debug_CallstackEntry;

typedef struct _debug_Locals {
    pb_callback_t values;
} debug_Locals;

/* The oneof tag is the value type, so a separate type enum and a decimal
 string are unnecessary. Fixed-width fields preserve WebAssembly bits and
 are fast to construct on the MCU. */
typedef struct _debug_Value {
    pb_size_t which_data;
    union {
        uint32_t i32_bits;
        uint64_t i64_bits;
        uint32_t f32_bits;
        uint64_t f64_bits;
        pb_callback_t raw;
    } data;
    uint32_t index;
} debug_Value;

typedef struct _debug_ValueUpdate {
    uint32_t index;
    bool has_value;
    debug_Value value;
} debug_ValueUpdate;

typedef struct _debug_CallbackMapping {
    pb_callback_t entries;
} debug_CallbackMapping;

typedef struct _debug_CallbackEntry {
    pb_callback_t topic;
    pb_callback_t table_indexes;
} debug_CallbackEntry;

typedef struct _debug_Event {
    pb_callback_t topic;
    pb_callback_t payload;
} debug_Event;

typedef struct _debug_Range {
    uint32_t start;
    uint32_t end;
} debug_Range;

typedef struct _debug_Function {
    uint32_t function_index;
    bool has_range;
    debug_Range range;
    bool has_locals;
    debug_Locals locals;
    pb_callback_t instructions;
} debug_Function;

typedef struct _debug_EventsQueue {
    /* Total events in the queue; this can exceed the returned slice length. */
    uint32_t total_count;
    pb_callback_t events;
    bool has_range;
    debug_Range range;
} debug_EventsQueue;

typedef struct _debug_ModuleUpdate {
    pb_callback_t wasm;
} debug_ModuleUpdate;

typedef struct _debug_IndexedValues {
    pb_callback_t values;
} debug_IndexedValues;

typedef struct _debug_SnapshotPolicyConfig {
    debug_SnapshotPolicy policy;
    uint32_t interval;
    uint32_t minimum_return_count;
    pb_callback_t selected_state;
} debug_SnapshotPolicyConfig;

typedef struct _debug_Override {
    pb_callback_t primitive_name;
    pb_callback_t argument_words;
    uint32_t result;
} debug_Override;

typedef struct _debug_OperationResult {
    debug_Command command;
    bool success;
} debug_OperationResult;

typedef struct _debug_RemoteFunctionResult {
    bool success;
    pb_callback_t results;
    pb_callback_t error;
} debug_RemoteFunctionResult;

typedef struct _debug_TableState {
    uint32_t initial;
    uint32_t maximum;
    pb_callback_t entries;
} debug_TableState;

typedef struct _debug_MemoryState {
    uint32_t initial;
    uint32_t maximum;
    uint32_t pages;
    pb_callback_t bytes;
} debug_MemoryState;

typedef struct _debug_Snapshot {
    uint32_t program_counter;
    debug_State state;
    pb_callback_t breakpoints;
    pb_callback_t functions;
    pb_callback_t callstack;
    bool has_locals;
    debug_Locals locals;
    bool has_queue;
    debug_EventsQueue queue;
    bool has_callbacks;
    debug_CallbackMapping callbacks;
    pb_callback_t globals;
    pb_callback_t stack;
    bool has_table;
    debug_TableState table;
    bool has_memory;
    debug_MemoryState memory;
    pb_callback_t branch_table;
    pb_callback_t io;
    pb_callback_t overrides;
    uint32_t heap_used;
} debug_Snapshot;

typedef struct _debug_Checkpoint {
    uint32_t instruction_count;
    bool has_primitive_call;
    uint32_t primitive_function_index;
    pb_callback_t arguments;
    pb_callback_t results;
    bool has_snapshot;
    debug_Snapshot snapshot;
} debug_Checkpoint;

typedef struct _debug_IOState {
    pb_callback_t key;
    bool output;
    int32_t value;
} debug_IOState;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _debug_Command_MIN debug_Command_COMMAND_RUN
#define _debug_Command_MAX debug_Command_COMMAND_REMOVE_OVERRIDE
#define _debug_Command_ARRAYSIZE ((debug_Command)(debug_Command_COMMAND_REMOVE_OVERRIDE+1))

#define _debug_NotificationType_MIN debug_NotificationType_NOTIFICATION_CONTINUED
#define _debug_NotificationType_MAX debug_NotificationType_NOTIFICATION_CHECKPOINT
#define _debug_NotificationType_ARRAYSIZE ((debug_NotificationType)(debug_NotificationType_NOTIFICATION_CHECKPOINT+1))

#define _debug_State_MIN debug_State_STATE_WARDUINO_RUN
#define _debug_State_MAX debug_State_STATE_PROXY_HALT
#define _debug_State_ARRAYSIZE ((debug_State)(debug_State_STATE_PROXY_HALT+1))

#define _debug_SnapshotPolicy_MIN debug_SnapshotPolicy_SNAPSHOT_POLICY_NONE
#define _debug_SnapshotPolicy_MAX debug_SnapshotPolicy_SNAPSHOT_POLICY_CHECKPOINTING
#define _debug_SnapshotPolicy_ARRAYSIZE ((debug_SnapshotPolicy)(debug_SnapshotPolicy_SNAPSHOT_POLICY_CHECKPOINTING+1))









#define debug_Snapshot_state_ENUMTYPE debug_State













#define debug_SnapshotPolicyConfig_policy_ENUMTYPE debug_SnapshotPolicy


#define debug_OperationResult_command_ENUMTYPE debug_Command







/* Initializer values for message structs */
#define debug_CodeLocation_init_default          {0, 0}
#define debug_Breakpoint_init_default            {false, debug_CodeLocation_init_default}
#define debug_HitBreakpoint_init_default         {false, debug_CodeLocation_init_default}
#define debug_NewEvent_init_default              {0}
#define debug_ContinueFor_init_default           {0}
#define debug_Inspect_init_default               {{{NULL}, NULL}}
#define debug_FunctionRef_init_default           {0}
#define debug_ValueUpdate_init_default           {0, false, debug_Value_init_default}
#define debug_Snapshot_init_default              {0, _debug_State_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, debug_Locals_init_default, false, debug_EventsQueue_init_default, false, debug_CallbackMapping_init_default, {{NULL}, NULL}, {{NULL}, NULL}, false, debug_TableState_init_default, false, debug_MemoryState_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define debug_Function_init_default              {0, false, debug_Range_init_default, false, debug_Locals_init_default, {{NULL}, NULL}}
#define debug_RemoteFunctionCall_init_default    {0, {{NULL}, NULL}}
#define debug_CallstackEntry_init_default        {0, 0, 0, 0, 0, 0}
#define debug_Locals_init_default                {{{NULL}, NULL}}
#define debug_Value_init_default                 {0, {0}, 0}
#define debug_CallbackMapping_init_default       {{{NULL}, NULL}}
#define debug_CallbackEntry_init_default         {{{NULL}, NULL}, {{NULL}, NULL}}
#define debug_EventsQueue_init_default           {0, {{NULL}, NULL}, false, debug_Range_init_default}
#define debug_Event_init_default                 {{{NULL}, NULL}, {{NULL}, NULL}}
#define debug_Range_init_default                 {0, 0}
#define debug_ModuleUpdate_init_default          {{{NULL}, NULL}}
#define debug_IndexedValues_init_default         {{{NULL}, NULL}}
#define debug_SnapshotPolicyConfig_init_default  {_debug_SnapshotPolicy_MIN, 0, 0, {{NULL}, NULL}}
#define debug_Override_init_default              {{{NULL}, NULL}, {{NULL}, NULL}, 0}
#define debug_OperationResult_init_default       {_debug_Command_MIN, 0}
#define debug_RemoteFunctionResult_init_default  {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define debug_Checkpoint_init_default            {0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, debug_Snapshot_init_default}
#define debug_TableState_init_default            {0, 0, {{NULL}, NULL}}
#define debug_MemoryState_init_default           {0, 0, 0, {{NULL}, NULL}}
#define debug_IOState_init_default               {{{NULL}, NULL}, 0, 0}
#define debug_CodeLocation_init_zero             {0, 0}
#define debug_Breakpoint_init_zero               {false, debug_CodeLocation_init_zero}
#define debug_HitBreakpoint_init_zero            {false, debug_CodeLocation_init_zero}
#define debug_NewEvent_init_zero                 {0}
#define debug_ContinueFor_init_zero              {0}
#define debug_Inspect_init_zero                  {{{NULL}, NULL}}
#define debug_FunctionRef_init_zero              {0}
#define debug_ValueUpdate_init_zero              {0, false, debug_Value_init_zero}
#define debug_Snapshot_init_zero                 {0, _debug_State_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, debug_Locals_init_zero, false, debug_EventsQueue_init_zero, false, debug_CallbackMapping_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, false, debug_TableState_init_zero, false, debug_MemoryState_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define debug_Function_init_zero                 {0, false, debug_Range_init_zero, false, debug_Locals_init_zero, {{NULL}, NULL}}
#define debug_RemoteFunctionCall_init_zero       {0, {{NULL}, NULL}}
#define debug_CallstackEntry_init_zero           {0, 0, 0, 0, 0, 0}
#define debug_Locals_init_zero                   {{{NULL}, NULL}}
#define debug_Value_init_zero                    {0, {0}, 0}
#define debug_CallbackMapping_init_zero          {{{NULL}, NULL}}
#define debug_CallbackEntry_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}}
#define debug_EventsQueue_init_zero              {0, {{NULL}, NULL}, false, debug_Range_init_zero}
#define debug_Event_init_zero                    {{{NULL}, NULL}, {{NULL}, NULL}}
#define debug_Range_init_zero                    {0, 0}
#define debug_ModuleUpdate_init_zero             {{{NULL}, NULL}}
#define debug_IndexedValues_init_zero            {{{NULL}, NULL}}
#define debug_SnapshotPolicyConfig_init_zero     {_debug_SnapshotPolicy_MIN, 0, 0, {{NULL}, NULL}}
#define debug_Override_init_zero                 {{{NULL}, NULL}, {{NULL}, NULL}, 0}
#define debug_OperationResult_init_zero          {_debug_Command_MIN, 0}
#define debug_RemoteFunctionResult_init_zero     {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define debug_Checkpoint_init_zero               {0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, debug_Snapshot_init_zero}
#define debug_TableState_init_zero               {0, 0, {{NULL}, NULL}}
#define debug_MemoryState_init_zero              {0, 0, 0, {{NULL}, NULL}}
#define debug_IOState_init_zero                  {{{NULL}, NULL}, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define debug_CodeLocation_module_index_tag      1
#define debug_CodeLocation_program_counter_tag   2
#define debug_Breakpoint_location_tag            1
#define debug_HitBreakpoint_location_tag         1
#define debug_ContinueFor_count_tag              1
#define debug_Inspect_state_tag                  1
#define debug_FunctionRef_function_index_tag     1
#define debug_RemoteFunctionCall_function_index_tag 1
#define debug_RemoteFunctionCall_arguments_tag   2
#define debug_CallstackEntry_type_tag            1
#define debug_CallstackEntry_function_index_tag  2
#define debug_CallstackEntry_stack_pointer_tag   3
#define debug_CallstackEntry_frame_pointer_tag   4
#define debug_CallstackEntry_start_tag           5
#define debug_CallstackEntry_return_address_tag  6
#define debug_Locals_values_tag                  1
#define debug_Value_i32_bits_tag                 1
#define debug_Value_i64_bits_tag                 2
#define debug_Value_f32_bits_tag                 3
#define debug_Value_f64_bits_tag                 4
#define debug_Value_raw_tag                      5
#define debug_Value_index_tag                    6
#define debug_ValueUpdate_index_tag              1
#define debug_ValueUpdate_value_tag              2
#define debug_CallbackMapping_entries_tag        1
#define debug_CallbackEntry_topic_tag            1
#define debug_CallbackEntry_table_indexes_tag    2
#define debug_Event_topic_tag                    1
#define debug_Event_payload_tag                  2
#define debug_Range_start_tag                    1
#define debug_Range_end_tag                      2
#define debug_Function_function_index_tag        1
#define debug_Function_range_tag                 2
#define debug_Function_locals_tag                3
#define debug_Function_instructions_tag          4
#define debug_EventsQueue_total_count_tag        1
#define debug_EventsQueue_events_tag             2
#define debug_EventsQueue_range_tag              3
#define debug_ModuleUpdate_wasm_tag              1
#define debug_IndexedValues_values_tag           1
#define debug_SnapshotPolicyConfig_policy_tag    1
#define debug_SnapshotPolicyConfig_interval_tag  2
#define debug_SnapshotPolicyConfig_minimum_return_count_tag 3
#define debug_SnapshotPolicyConfig_selected_state_tag 4
#define debug_Override_primitive_name_tag        1
#define debug_Override_argument_words_tag        2
#define debug_Override_result_tag                3
#define debug_OperationResult_command_tag        1
#define debug_OperationResult_success_tag        2
#define debug_RemoteFunctionResult_success_tag   1
#define debug_RemoteFunctionResult_results_tag   2
#define debug_RemoteFunctionResult_error_tag     3
#define debug_TableState_initial_tag             1
#define debug_TableState_maximum_tag             2
#define debug_TableState_entries_tag             3
#define debug_MemoryState_initial_tag            1
#define debug_MemoryState_maximum_tag            2
#define debug_MemoryState_pages_tag              3
#define debug_MemoryState_bytes_tag              4
#define debug_Snapshot_program_counter_tag       1
#define debug_Snapshot_state_tag                 2
#define debug_Snapshot_breakpoints_tag           3
#define debug_Snapshot_functions_tag             4
#define debug_Snapshot_callstack_tag             5
#define debug_Snapshot_locals_tag                6
#define debug_Snapshot_queue_tag                 7
#define debug_Snapshot_callbacks_tag             8
#define debug_Snapshot_globals_tag               9
#define debug_Snapshot_stack_tag                 10
#define debug_Snapshot_table_tag                 11
#define debug_Snapshot_memory_tag                12
#define debug_Snapshot_branch_table_tag          13
#define debug_Snapshot_io_tag                    14
#define debug_Snapshot_overrides_tag             15
#define debug_Snapshot_heap_used_tag             16
#define debug_Checkpoint_instruction_count_tag   1
#define debug_Checkpoint_has_primitive_call_tag  2
#define debug_Checkpoint_primitive_function_index_tag 3
#define debug_Checkpoint_arguments_tag           4
#define debug_Checkpoint_results_tag             5
#define debug_Checkpoint_snapshot_tag            6
#define debug_IOState_key_tag                    1
#define debug_IOState_output_tag                 2
#define debug_IOState_value_tag                  3

/* Struct field encoding specification for nanopb */
#define debug_CodeLocation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   module_index,      1) \
X(a, STATIC,   SINGULAR, UINT32,   program_counter,   2)
#define debug_CodeLocation_CALLBACK NULL
#define debug_CodeLocation_DEFAULT NULL

#define debug_Breakpoint_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  location,          1)
#define debug_Breakpoint_CALLBACK NULL
#define debug_Breakpoint_DEFAULT NULL
#define debug_Breakpoint_location_MSGTYPE debug_CodeLocation

#define debug_HitBreakpoint_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  location,          1)
#define debug_HitBreakpoint_CALLBACK NULL
#define debug_HitBreakpoint_DEFAULT NULL
#define debug_HitBreakpoint_location_MSGTYPE debug_CodeLocation

#define debug_NewEvent_FIELDLIST(X, a) \

#define debug_NewEvent_CALLBACK NULL
#define debug_NewEvent_DEFAULT NULL

#define debug_ContinueFor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   count,             1)
#define debug_ContinueFor_CALLBACK NULL
#define debug_ContinueFor_DEFAULT NULL

#define debug_Inspect_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    state,             1)
#define debug_Inspect_CALLBACK pb_default_field_callback
#define debug_Inspect_DEFAULT NULL

#define debug_FunctionRef_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   function_index,    1)
#define debug_FunctionRef_CALLBACK NULL
#define debug_FunctionRef_DEFAULT NULL

#define debug_ValueUpdate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   index,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define debug_ValueUpdate_CALLBACK NULL
#define debug_ValueUpdate_DEFAULT NULL
#define debug_ValueUpdate_value_MSGTYPE debug_Value

#define debug_Snapshot_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   program_counter,   1) \
X(a, STATIC,   SINGULAR, UENUM,    state,             2) \
X(a, CALLBACK, REPEATED, UINT32,   breakpoints,       3) \
X(a, CALLBACK, REPEATED, MESSAGE,  functions,         4) \
X(a, CALLBACK, REPEATED, MESSAGE,  callstack,         5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  locals,            6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  queue,             7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  callbacks,         8) \
X(a, CALLBACK, REPEATED, MESSAGE,  globals,           9) \
X(a, CALLBACK, REPEATED, MESSAGE,  stack,            10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  table,            11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  memory,           12) \
X(a, CALLBACK, REPEATED, UINT32,   branch_table,     13) \
X(a, CALLBACK, REPEATED, MESSAGE,  io,               14) \
X(a, CALLBACK, REPEATED, MESSAGE,  overrides,        15) \
X(a, STATIC,   SINGULAR, UINT32,   heap_used,        16)
#define debug_Snapshot_CALLBACK pb_default_field_callback
#define debug_Snapshot_DEFAULT NULL
#define debug_Snapshot_functions_MSGTYPE debug_Function
#define debug_Snapshot_callstack_MSGTYPE debug_CallstackEntry
#define debug_Snapshot_locals_MSGTYPE debug_Locals
#define debug_Snapshot_queue_MSGTYPE debug_EventsQueue
#define debug_Snapshot_callbacks_MSGTYPE debug_CallbackMapping
#define debug_Snapshot_globals_MSGTYPE debug_Value
#define debug_Snapshot_stack_MSGTYPE debug_Value
#define debug_Snapshot_table_MSGTYPE debug_TableState
#define debug_Snapshot_memory_MSGTYPE debug_MemoryState
#define debug_Snapshot_io_MSGTYPE debug_IOState
#define debug_Snapshot_overrides_MSGTYPE debug_Override

#define debug_Function_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   function_index,    1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  range,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  locals,            3) \
X(a, CALLBACK, SINGULAR, BYTES,    instructions,      4)
#define debug_Function_CALLBACK pb_default_field_callback
#define debug_Function_DEFAULT NULL
#define debug_Function_range_MSGTYPE debug_Range
#define debug_Function_locals_MSGTYPE debug_Locals

#define debug_RemoteFunctionCall_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   function_index,    1) \
X(a, CALLBACK, REPEATED, MESSAGE,  arguments,         2)
#define debug_RemoteFunctionCall_CALLBACK pb_default_field_callback
#define debug_RemoteFunctionCall_DEFAULT NULL
#define debug_RemoteFunctionCall_arguments_MSGTYPE debug_Value

#define debug_CallstackEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type,              1) \
X(a, STATIC,   SINGULAR, UINT32,   function_index,    2) \
X(a, STATIC,   SINGULAR, UINT32,   stack_pointer,     3) \
X(a, STATIC,   SINGULAR, UINT32,   frame_pointer,     4) \
X(a, STATIC,   SINGULAR, UINT32,   start,             5) \
X(a, STATIC,   SINGULAR, UINT32,   return_address,    6)
#define debug_CallstackEntry_CALLBACK NULL
#define debug_CallstackEntry_DEFAULT NULL

#define debug_Locals_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  values,            1)
#define debug_Locals_CALLBACK pb_default_field_callback
#define debug_Locals_DEFAULT NULL
#define debug_Locals_values_MSGTYPE debug_Value

#define debug_Value_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    FIXED32,  (data,i32_bits,data.i32_bits),   1) \
X(a, STATIC,   ONEOF,    FIXED64,  (data,i64_bits,data.i64_bits),   2) \
X(a, STATIC,   ONEOF,    FIXED32,  (data,f32_bits,data.f32_bits),   3) \
X(a, STATIC,   ONEOF,    FIXED64,  (data,f64_bits,data.f64_bits),   4) \
X(a, CALLBACK, ONEOF,    BYTES,    (data,raw,data.raw),   5) \
X(a, STATIC,   SINGULAR, UINT32,   index,             6)
#define debug_Value_CALLBACK pb_default_field_callback
#define debug_Value_DEFAULT NULL

#define debug_CallbackMapping_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  entries,           1)
#define debug_CallbackMapping_CALLBACK pb_default_field_callback
#define debug_CallbackMapping_DEFAULT NULL
#define debug_CallbackMapping_entries_MSGTYPE debug_CallbackEntry

#define debug_CallbackEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   topic,             1) \
X(a, CALLBACK, REPEATED, UINT32,   table_indexes,     2)
#define debug_CallbackEntry_CALLBACK pb_default_field_callback
#define debug_CallbackEntry_DEFAULT NULL

#define debug_EventsQueue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   total_count,       1) \
X(a, CALLBACK, REPEATED, MESSAGE,  events,            2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  range,             3)
#define debug_EventsQueue_CALLBACK pb_default_field_callback
#define debug_EventsQueue_DEFAULT NULL
#define debug_EventsQueue_events_MSGTYPE debug_Event
#define debug_EventsQueue_range_MSGTYPE debug_Range

#define debug_Event_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   topic,             1) \
X(a, CALLBACK, SINGULAR, BYTES,    payload,           2)
#define debug_Event_CALLBACK pb_default_field_callback
#define debug_Event_DEFAULT NULL

#define debug_Range_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   start,             1) \
X(a, STATIC,   SINGULAR, UINT32,   end,               2)
#define debug_Range_CALLBACK NULL
#define debug_Range_DEFAULT NULL

#define debug_ModuleUpdate_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    wasm,              1)
#define debug_ModuleUpdate_CALLBACK pb_default_field_callback
#define debug_ModuleUpdate_DEFAULT NULL

#define debug_IndexedValues_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  values,            1)
#define debug_IndexedValues_CALLBACK pb_default_field_callback
#define debug_IndexedValues_DEFAULT NULL
#define debug_IndexedValues_values_MSGTYPE debug_Value

#define debug_SnapshotPolicyConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    policy,            1) \
X(a, STATIC,   SINGULAR, UINT32,   interval,          2) \
X(a, STATIC,   SINGULAR, UINT32,   minimum_return_count,   3) \
X(a, CALLBACK, SINGULAR, BYTES,    selected_state,    4)
#define debug_SnapshotPolicyConfig_CALLBACK pb_default_field_callback
#define debug_SnapshotPolicyConfig_DEFAULT NULL

#define debug_Override_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   primitive_name,    1) \
X(a, CALLBACK, REPEATED, FIXED32,  argument_words,    2) \
X(a, STATIC,   SINGULAR, FIXED32,  result,            3)
#define debug_Override_CALLBACK pb_default_field_callback
#define debug_Override_DEFAULT NULL

#define debug_OperationResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    command,           1) \
X(a, STATIC,   SINGULAR, BOOL,     success,           2)
#define debug_OperationResult_CALLBACK NULL
#define debug_OperationResult_DEFAULT NULL

#define debug_RemoteFunctionResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, REPEATED, MESSAGE,  results,           2) \
X(a, CALLBACK, SINGULAR, BYTES,    error,             3)
#define debug_RemoteFunctionResult_CALLBACK pb_default_field_callback
#define debug_RemoteFunctionResult_DEFAULT NULL
#define debug_RemoteFunctionResult_results_MSGTYPE debug_Value

#define debug_Checkpoint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   instruction_count,   1) \
X(a, STATIC,   SINGULAR, BOOL,     has_primitive_call,   2) \
X(a, STATIC,   SINGULAR, UINT32,   primitive_function_index,   3) \
X(a, CALLBACK, REPEATED, MESSAGE,  arguments,         4) \
X(a, CALLBACK, REPEATED, MESSAGE,  results,           5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  snapshot,          6)
#define debug_Checkpoint_CALLBACK pb_default_field_callback
#define debug_Checkpoint_DEFAULT NULL
#define debug_Checkpoint_arguments_MSGTYPE debug_Value
#define debug_Checkpoint_results_MSGTYPE debug_Value
#define debug_Checkpoint_snapshot_MSGTYPE debug_Snapshot

#define debug_TableState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   initial,           1) \
X(a, STATIC,   SINGULAR, UINT32,   maximum,           2) \
X(a, CALLBACK, REPEATED, UINT32,   entries,           3)
#define debug_TableState_CALLBACK pb_default_field_callback
#define debug_TableState_DEFAULT NULL

#define debug_MemoryState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   initial,           1) \
X(a, STATIC,   SINGULAR, UINT32,   maximum,           2) \
X(a, STATIC,   SINGULAR, UINT32,   pages,             3) \
X(a, CALLBACK, SINGULAR, BYTES,    bytes,             4)
#define debug_MemoryState_CALLBACK pb_default_field_callback
#define debug_MemoryState_DEFAULT NULL

#define debug_IOState_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, BOOL,     output,            2) \
X(a, STATIC,   SINGULAR, SINT32,   value,             3)
#define debug_IOState_CALLBACK pb_default_field_callback
#define debug_IOState_DEFAULT NULL

extern const pb_msgdesc_t debug_CodeLocation_msg;
extern const pb_msgdesc_t debug_Breakpoint_msg;
extern const pb_msgdesc_t debug_HitBreakpoint_msg;
extern const pb_msgdesc_t debug_NewEvent_msg;
extern const pb_msgdesc_t debug_ContinueFor_msg;
extern const pb_msgdesc_t debug_Inspect_msg;
extern const pb_msgdesc_t debug_FunctionRef_msg;
extern const pb_msgdesc_t debug_ValueUpdate_msg;
extern const pb_msgdesc_t debug_Snapshot_msg;
extern const pb_msgdesc_t debug_Function_msg;
extern const pb_msgdesc_t debug_RemoteFunctionCall_msg;
extern const pb_msgdesc_t debug_CallstackEntry_msg;
extern const pb_msgdesc_t debug_Locals_msg;
extern const pb_msgdesc_t debug_Value_msg;
extern const pb_msgdesc_t debug_CallbackMapping_msg;
extern const pb_msgdesc_t debug_CallbackEntry_msg;
extern const pb_msgdesc_t debug_EventsQueue_msg;
extern const pb_msgdesc_t debug_Event_msg;
extern const pb_msgdesc_t debug_Range_msg;
extern const pb_msgdesc_t debug_ModuleUpdate_msg;
extern const pb_msgdesc_t debug_IndexedValues_msg;
extern const pb_msgdesc_t debug_SnapshotPolicyConfig_msg;
extern const pb_msgdesc_t debug_Override_msg;
extern const pb_msgdesc_t debug_OperationResult_msg;
extern const pb_msgdesc_t debug_RemoteFunctionResult_msg;
extern const pb_msgdesc_t debug_Checkpoint_msg;
extern const pb_msgdesc_t debug_TableState_msg;
extern const pb_msgdesc_t debug_MemoryState_msg;
extern const pb_msgdesc_t debug_IOState_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define debug_CodeLocation_fields &debug_CodeLocation_msg
#define debug_Breakpoint_fields &debug_Breakpoint_msg
#define debug_HitBreakpoint_fields &debug_HitBreakpoint_msg
#define debug_NewEvent_fields &debug_NewEvent_msg
#define debug_ContinueFor_fields &debug_ContinueFor_msg
#define debug_Inspect_fields &debug_Inspect_msg
#define debug_FunctionRef_fields &debug_FunctionRef_msg
#define debug_ValueUpdate_fields &debug_ValueUpdate_msg
#define debug_Snapshot_fields &debug_Snapshot_msg
#define debug_Function_fields &debug_Function_msg
#define debug_RemoteFunctionCall_fields &debug_RemoteFunctionCall_msg
#define debug_CallstackEntry_fields &debug_CallstackEntry_msg
#define debug_Locals_fields &debug_Locals_msg
#define debug_Value_fields &debug_Value_msg
#define debug_CallbackMapping_fields &debug_CallbackMapping_msg
#define debug_CallbackEntry_fields &debug_CallbackEntry_msg
#define debug_EventsQueue_fields &debug_EventsQueue_msg
#define debug_Event_fields &debug_Event_msg
#define debug_Range_fields &debug_Range_msg
#define debug_ModuleUpdate_fields &debug_ModuleUpdate_msg
#define debug_IndexedValues_fields &debug_IndexedValues_msg
#define debug_SnapshotPolicyConfig_fields &debug_SnapshotPolicyConfig_msg
#define debug_Override_fields &debug_Override_msg
#define debug_OperationResult_fields &debug_OperationResult_msg
#define debug_RemoteFunctionResult_fields &debug_RemoteFunctionResult_msg
#define debug_Checkpoint_fields &debug_Checkpoint_msg
#define debug_TableState_fields &debug_TableState_msg
#define debug_MemoryState_fields &debug_MemoryState_msg
#define debug_IOState_fields &debug_IOState_msg

/* Maximum encoded size of messages (where known) */
/* debug_Inspect_size depends on runtime parameters */
/* debug_ValueUpdate_size depends on runtime parameters */
/* debug_Snapshot_size depends on runtime parameters */
/* debug_Function_size depends on runtime parameters */
/* debug_RemoteFunctionCall_size depends on runtime parameters */
/* debug_Locals_size depends on runtime parameters */
/* debug_Value_size depends on runtime parameters */
/* debug_CallbackMapping_size depends on runtime parameters */
/* debug_CallbackEntry_size depends on runtime parameters */
/* debug_EventsQueue_size depends on runtime parameters */
/* debug_Event_size depends on runtime parameters */
/* debug_ModuleUpdate_size depends on runtime parameters */
/* debug_IndexedValues_size depends on runtime parameters */
/* debug_SnapshotPolicyConfig_size depends on runtime parameters */
/* debug_Override_size depends on runtime parameters */
/* debug_RemoteFunctionResult_size depends on runtime parameters */
/* debug_Checkpoint_size depends on runtime parameters */
/* debug_TableState_size depends on runtime parameters */
/* debug_MemoryState_size depends on runtime parameters */
/* debug_IOState_size depends on runtime parameters */
#define DEBUG_DEBUG_PB_H_MAX_SIZE                debug_CallstackEntry_size
#define debug_Breakpoint_size                    14
#define debug_CallstackEntry_size                36
#define debug_CodeLocation_size                  12
#define debug_ContinueFor_size                   6
#define debug_FunctionRef_size                   6
#define debug_HitBreakpoint_size                 14
#define debug_NewEvent_size                      0
#define debug_OperationResult_size               4
#define debug_Range_size                         12

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
