/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "debug.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(debug_CodeLocation, debug_CodeLocation, AUTO)


PB_BIND(debug_Breakpoint, debug_Breakpoint, AUTO)


PB_BIND(debug_HitBreakpoint, debug_HitBreakpoint, AUTO)


PB_BIND(debug_NewEvent, debug_NewEvent, AUTO)


PB_BIND(debug_ContinueFor, debug_ContinueFor, AUTO)


PB_BIND(debug_Inspect, debug_Inspect, AUTO)


PB_BIND(debug_FunctionRef, debug_FunctionRef, AUTO)


PB_BIND(debug_ValueUpdate, debug_ValueUpdate, AUTO)


PB_BIND(debug_Snapshot, debug_Snapshot, 2)


PB_BIND(debug_Function, debug_Function, AUTO)


PB_BIND(debug_RemoteFunctionCall, debug_RemoteFunctionCall, AUTO)


PB_BIND(debug_CallstackEntry, debug_CallstackEntry, AUTO)


PB_BIND(debug_Locals, debug_Locals, AUTO)


PB_BIND(debug_Value, debug_Value, AUTO)


PB_BIND(debug_CallbackMapping, debug_CallbackMapping, AUTO)


PB_BIND(debug_CallbackEntry, debug_CallbackEntry, AUTO)


PB_BIND(debug_EventsQueue, debug_EventsQueue, AUTO)


PB_BIND(debug_Event, debug_Event, AUTO)


PB_BIND(debug_Range, debug_Range, AUTO)


PB_BIND(debug_ModuleUpdate, debug_ModuleUpdate, AUTO)


PB_BIND(debug_IndexedValues, debug_IndexedValues, AUTO)


PB_BIND(debug_SnapshotPolicyConfig, debug_SnapshotPolicyConfig, AUTO)


PB_BIND(debug_Override, debug_Override, AUTO)


PB_BIND(debug_OperationResult, debug_OperationResult, AUTO)


PB_BIND(debug_RemoteFunctionResult, debug_RemoteFunctionResult, AUTO)


PB_BIND(debug_Checkpoint, debug_Checkpoint, 2)


PB_BIND(debug_TableState, debug_TableState, AUTO)


PB_BIND(debug_MemoryState, debug_MemoryState, AUTO)


PB_BIND(debug_IOState, debug_IOState, AUTO)











