#!/usr/bin/sh
# Name:
# By Robbert Gurdeep Singh
################################################################################
BASEPATH="$( cd "$(dirname "$0")" ; cd .. ; pwd -L )"

arduino --upload $BASEPATH/arduino.ino --board "esp8266:esp8266:nodemcu:xtal=80,vt=flash,exception=disabled,ssl=all,eesz=4M,ip=lm2f,dbg=Disabled,lvl=None____,wipe=all,baud=115200"
