[package]
name = "warduino"
version = "0.1.0"
authors = ["Tom Lauwaerts <tom.lauwaerts@ugent.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
