name: Publish new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: 'warning'
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Update version"
        run: |
          sed -i "s/\(project(WARDuino VERSION \)[0-9]\+\.[0-9]\+\.[0-9]\+/\1$VERSION/" CMakeLists.txt
          sed -i "s/\(version=\)[0-9]\+\.[0-9]\+\.[0-9]\+/\1$VERSION/" library.properties
        env:
          VERSION: ${{ inputs.version }}

      - name: Update metadata
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          #git add CMakeLists.txt library.properties

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "🔖 Bump version to ${{ inputs.version }}"
          branch: release
          title: "Release for ${{ inputs.version }}"
          body: "This is an automated PR for the next release, version: ${{ inputs.version }}."

